# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'BlessingSMS' do

pod "AFNetworking", "~>2.5.4"
pod 'JSONKit', '~> 1.5pre'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'GDTMobSDK', "~>4.10.14"

end

